name: Lighthouse CI
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse
        timeout-minutes: 15
        uses: ./.github/actions/automated-lighthouse
        with:
          urls: |
            https://www.welovespeed.com/2023/
            https://www.welovespeed.com/2023/programme/
            https://www.welovespeed.com/2023/infos-pratiques/
            https://www.welovespeed.com/2023/merci/
          # budgetPath: ./budget.json # Lighthouse budget file
          # lighthousercPath: ./lighthouserc.json # Lighthouse configuration file
          googleSpreadsheetId: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          googleServiceAccountEmail: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          googlePrivateKey: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          # slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          # slackChannel: example-channel
        # Environment variables injected to the Pupeteer script
        env:
          EXAMPLE_ENV: example
